# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 13:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('logging_svc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hostip',
            field=models.GenericIPAddressField(default='0.0.0.0', unpack_ipv4=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='hostname',
            field=models.CharField(default='localhost', max_length=250, validators=[django.core.validators.RegexValidator(flags=[re.RegexFlag(2)], regex='^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='play',
            name='hostip',
            field=models.GenericIPAddressField(default='0.0.0.0', unpack_ipv4=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='play',
            name='hostname',
            field=models.CharField(default='localhost', max_length=250, validators=[django.core.validators.RegexValidator(flags=[re.RegexFlag(2)], regex='^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='hostip',
            field=models.GenericIPAddressField(default='0.0.0.0', unpack_ipv4=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='hostname',
            field=models.CharField(default='localhost', max_length=250, validators=[django.core.validators.RegexValidator(flags=[re.RegexFlag(2)], regex='^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$')]),
            preserve_default=False,
        ),
    ]
