# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('logging_svc', '0002_auto_20170515_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hostip',
            field=models.GenericIPAddressField(default='0.0.0.0', unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hostname',
            field=models.CharField(default='nohost', max_length=250, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag(2), regex='^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$')]),
        ),
        migrations.AlterField(
            model_name='play',
            name='hostip',
            field=models.GenericIPAddressField(default='0.0.0.0', unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='hostname',
            field=models.CharField(default='nohost', max_length=250, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag(2), regex='^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='hostip',
            field=models.GenericIPAddressField(default='0.0.0.0', unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='hostname',
            field=models.CharField(default='nohost', max_length=250, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag(2), regex='^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$')]),
        ),
    ]
