# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_svc', '0003_auto_20170515_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='play',
            name='user',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(default='unknown', max_length=150),
        ),
    ]
